#cards table
BEGIN;



CREATE TABLE public.cards (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id  integer NOT NULL
           REFERENCES public.users(id) ON DELETE CASCADE,
  number   varchar(19)  NOT NULL,            -- card number as text
  holder   varchar(100) NOT NULL,            -- cardholder name
  expiry   varchar(5)   NOT NULL,            -- MM/YY
  balance  numeric(12,2) NOT NULL DEFAULT 0, -- SGD balance
  design   varchar(50)  NOT NULL DEFAULT 'netscard1'
);

CREATE INDEX idx_cards_user_id ON public.cards(user_id);