BEGIN;


DROP TABLE IF EXISTS public.transactions CASCADE;

CREATE TABLE public.transactions (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   integer REFERENCES public.users(id) ON DELETE CASCADE, -- Track which user made the transaction
  card_id   integer REFERENCES public.cards(id) ON DELETE CASCADE, -- Allow NULL for external payments
  name      varchar(100) NOT NULL,
  "time"    timestamp without time zone NOT NULL DEFAULT NOW(),
  amount    numeric(12,2) NOT NULL,
  type      varchar(10)  NOT NULL,                 -- 'income' | 'expense'
  CONSTRAINT transactions_type_chk    CHECK (type IN ('income','expense')),
  CONSTRAINT transactions_amount_pos  CHECK (amount >= 0)
);


CREATE INDEX idx_tx_user_time ON public.transactions(user_id, "time");
CREATE INDEX idx_tx_card_time ON public.transactions(card_id, "time");
CREATE INDEX idx_tx_type      ON public.transactions(type);
CREATE INDEX idx_tx_time      ON public.transactions("time");

COMMIT;
