BEGIN;



CREATE TABLE IF NOT EXISTS public.users (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       varchar(50)  NOT NULL,
  password_hash  varchar(255) NOT NULL
);


DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'users_username_key'
  ) THEN
    ALTER TABLE public.users
      ADD CONSTRAINT users_username_key UNIQUE (username);
  END IF;
END$$;

COMMIT;
